import fs from 'node:fs';
const specs=[
['Generative AI','Computer Science',['Large Language Models','Retrieval-Augmented Generation','Responsible AI'],['clinical question answering','multilingual learning assistants','scientific literature discovery','accessible education','trusted document search'],['retrieval-augmented language models','grounded text generation','human-reviewed evaluation'],['genai','llm','llms','rag','generative artificial intelligence','language model']],
['Cybersecurity','Computer Science',['Network Security','Machine Learning','Privacy'],['network intrusion detection','secure connected hospitals','phishing detection','privacy-preserving threat analysis','cloud access security'],['anomaly detection','federated threat modeling','explainable classifiers'],['cyber','security','cyber security','cyber attacks','network attacks']],
['Natural Language Processing','Computer Science',['Information Retrieval','Multilingual NLP','Text Analytics'],['low-resource language translation','research question answering','student feedback analysis','clinical text extraction','cross-lingual document retrieval'],['transformer encoders','contrastive text representations','passage reranking'],['nlp','language processing','natural language','text mining','translation']],
['Computer Vision','Computer Science',['Deep Learning','Image Analysis','Pattern Recognition'],['medical image segmentation','crop disease recognition','accessible scene understanding','industrial defect inspection','satellite image analysis'],['vision transformers','convolutional networks','self-supervised image learning'],['cv','image recognition','image processing','visual recognition','vision']],
['Healthcare AI','Biomedical Engineering',['Machine Learning','Biomedical Informatics','Explainable AI'],['early disease screening','clinical decision support','patient monitoring','medical imaging','hospital resource planning'],['interpretable predictive models','uncertainty-aware classification','multimodal learning'],['healthcare','health care','medicine','medical','clinical','disease','diagnosis']],
['Robotics','Mechanical Engineering',['Control Systems','Autonomous Systems','Sensor Fusion'],['warehouse navigation','assistive robot interaction','precision agriculture','collaborative manufacturing','autonomous inspection'],['reinforcement learning','model predictive control','multi-sensor fusion'],['robots','robot','autonomous','navigation']],
['Internet of Things','Electrical Engineering',['Edge Computing','Sensor Networks','Embedded Systems'],['smart building monitoring','wearable health sensing','water quality monitoring','connected agriculture','energy-efficient factories'],['edge inference','adaptive sensor scheduling','low-power communication'],['iot','internet of things','sensors','connected devices','edge']],
['Data Science','Mathematics & Computing',['Statistical Learning','Data Engineering','Time Series'],['urban mobility forecasting','research trend mapping','energy demand prediction','fair public service allocation','supply chain planning'],['probabilistic forecasting','graph-based analysis','causal inference'],['data analytics','analytics','statistics','forecasting','big data']],
['Cloud Computing','Computer Science',['Distributed Systems','Resource Scheduling','Reliability'],['research workflow orchestration','sustainable data centers','scalable academic search','reliable edge-cloud services','distributed training'],['adaptive workload scheduling','fault-tolerant processing','resource-aware optimization'],['cloud','distributed computing','serverless','data centers','scalability']],
['Machine Learning','Mathematics & Computing',['Artificial Intelligence','Optimization','Explainable AI'],['low-data scientific discovery','reliable educational assessment','interpretable risk modeling','sustainable materials screening','robust sensor prediction'],['few-shot learning','calibrated ensembles','representation learning'],['ml','artificial intelligence','ai','deep learning','neural networks','predictive models']]
];
const topics=specs.map(([name,department,sub,applications,methods,aliases])=>({name,department,sub,applications,methods,aliases}));
const first='Ananya Arjun Meera Rohan Kavya Nikhil Sara Dev Ishita Aarav Neha Vikram Priya Aditya Nandini Kabir Leela Rahul Aisha Kiran Tanvi Varun Diya Siddharth Maya Riya Ishan Sana Pranav Tara Aditi Rehan Suhani Manav Zoya Avni Dhruv Naina Yash Siya Anika Vihaan Mira Krish Noor Jaya Samir Pallavi Rishi Esha'.split(' ');
const last='Sharma Rao Iyer Mehta Nair Sen Kapoor Menon Patel Das'.split(' ');
const faculty=[],publications=[],records=[];
for(let i=0;i<50;i++){
 const t=topics[Math.floor(i/5)],id=`FAC-${String(i+1).padStart(3,'0')}`,name=`Dr. ${first[i]} ${last[i%10]}`;
 const f={id,name,aliases:[`${first[i][0]}. ${last[i%10]}`,name.replace('Dr. ','Prof. ')],designation:['Associate Professor','Professor','Assistant Professor'][i%3],department:t.department,institution:['Westbridge Research University','Meridian Institute of Technology','Northfield University'][i%3]+' (fictional)',statedExpertise:[t.name,...t.sub.slice(0,2)],inferredExpertise:[t.sub[2],...(i===0?['Healthcare AI']:[])],bio:`${name} studies ${t.applications[i%5]}, with an emphasis on ${t.methods[i%3]}. This fictional profile illustrates how research evidence can make academic collaboration easier.`,project:`${t.applications[i%5][0].toUpperCase()+t.applications[i%5].slice(1)} research initiative`,synthetic:true,profileSource:`/faculty/${id}`};
 faculty.push(f);
 for(let j=0;j<3;j++){
  const pid=`PUB-${String(i*3+j+1).padStart(3,'0')}`,method=t.methods[j],application=t.applications[i%5],title=`${method[0].toUpperCase()+method.slice(1)} for ${application}${j===1?': a comparative study':j===2?': an evidence-led framework':''}`;
  const passage=`We investigate ${method} for ${application}. The framework connects ${t.name.toLowerCase()} with ${t.sub[j].toLowerCase()} to support interpretable, reproducible research.`;
  const p={id:pid,facultyId:id,title,year:2021+((i+j)%6),type:j===1?'Journal':'Conference',venue:`Demo ${j===1?'Journal':'Symposium'} on ${t.name}`,abstract:`${passage} The proposed study describes data preparation, baseline comparisons and error analysis. Evaluation would examine performance across varied conditions and document limitations before practical use. This abstract is synthetic and does not report real experimental findings.`,passage,topics:[t.name,t.sub[j],...(i===0?['Healthcare AI']:[])],sourceUrl:`/publications/${pid}`,doi:null,synthetic:true};
  publications.push(p);records.push({record_id:pid,faculty_id:id,faculty_name:name,name_variants:f.aliases,designation:f.designation,department:f.department,institution:f.institution,stated_expertise:f.statedExpertise,inferred_expertise:f.inferredExpertise,project:f.project,publication_title:title,publication_year:p.year,publication_type:p.type,venue:p.venue,abstract:p.abstract,evidence_passage:passage,research_topics:p.topics,source_path:p.sourceUrl,doi:null,is_synthetic:true});
 }
}
const metadata={title:'Faculty Discovery Synthetic Research Corpus',version:'1.0',recordCount:150,facultyCount:50,topicCount:10,license:'CC0-1.0',provenance:'Generated fictional demonstration data. Not real faculty, publications, consent records or experimental results.',sourceLinkPolicy:'Relative links resolve to local demo publication pages. No external DOI is fabricated.'};
fs.writeFileSync('lib/data/corpus.json',JSON.stringify({metadata,topics,faculty,publications},null,2));
fs.writeFileSync('public/dataset/faculty-research-150.json',JSON.stringify({metadata,records},null,2));
fs.writeFileSync('public/dataset/faculty-research-150.jsonl',records.map(x=>JSON.stringify(x)).join('\n')+'\n');
fs.writeFileSync('public/dataset/README.md',`# Faculty Discovery — 150-record synthetic dataset\n\n150 publication-level records linked by faculty_id to 50 fictional faculty across 10 topics. All names, institutions, titles, abstracts and passages are synthetic; any resemblance is coincidental. This is demonstration data, not a real academic corpus or valid evidence for research claims.\n\n## Files\n- faculty-research-150.json: metadata plus records, UTF-8.\n- faculty-research-150.jsonl: one record per line for ingestion.\n- evaluation.json: ten topic queries evaluated against topic-based synthetic labels, not independent human judgments.\n\n## Schema\nEach record has record_id (unique publication key), faculty_id (author key), faculty_name, name_variants, designation, department, institution, stated_expertise (profile labels), inferred_expertise (publication-related labels), project, publication_title, publication_year (2021–2026), publication_type, venue, abstract, evidence_passage, research_topics, source_path, doi (null), is_synthetic (true). Arrays remain native JSON arrays. Faculty fields repeat consistently across the three publications belonging to each faculty.\n\n## Use\nJoin records by faculty_id, never by name alone. source_path opens the local fictional publication; it is not a real citation. Regenerate with scripts/generate-corpus.mjs in the website source. CC0-1.0 for generated data.\n\n## Search\nThe demo combines BM25 keyword ranking and cosine similarity over ten explicit, alias-normalized topic dimensions. This interpretable concept vector is not a pretrained semantic embedding model. Rank fusion combines eligible candidates, then aggregates publications by faculty. Explanations quote stored passages; no LLM is connected. Production use needs a consented real corpus, pretrained embeddings, author disambiguation and independent relevance judgments.\n`);
console.log(`Generated ${records.length} records, ${faculty.length} faculty and ${topics.length} topics.`);
